import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import styles from "./page.module.css";
import Header from "../../components/header/header";
import Sidebar from "../../components/sidebar/sidebar";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "700"],
  variable: "--roboto",
});

export const metadata: Metadata = {
  title: "Kind Parks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={roboto.className}>
        <Header />
        <Sidebar />
        <div className={styles.inner__content_area}>{children}</div>
      </body>
    </html>
  );
}
